export const GET_RANDOM_WALK = 'GET_RANDOM_WALK'
export const SELECT_WALK = 'SELECT_WALK'

export const GET_RANDOM_BIKE = 'GET_RANDOM_BIKE'
export const SELECT_BIKE = 'SELECT_BIKE'

export const GET_RANDOM_MOTORCYCLE = 'GET_RANDOM_MOTORCYCLE'
export const SELECT_MOTORCYCLE = 'SELECT_MOTORCYCLE'

export const GET_RANDOM_CAR = 'GET_RANDOM_CAR'
export const SELECT_CAR = 'SELECT_CAR'
