export const GET_RANDOM_WALK = 'GET_RANDOM_WALK'
export const SELECT_WALK = 'SELECT_WALK'

export const GET_RANDOM_BIKE = 'GET_RANDOM_BIKE'
export const SELECT_BIKE = 'SELECT_BIKE'

export const GET_RANDOM_MOTORCYCLE = 'GET_RANDOM_MOTORCYCLE'
export const SELECT_MOTORCYCLE = 'SELECT_MOTORCYCLE'

export const GET_RANDOM_CAR = 'GET_RANDOM_CAR'
export const SELECT_CAR = 'SELECT_CAR'

export const FETCH_BOARD_LIST = 'FETCH_BOARD_LIST'
export const FETCH_BOARD = 'FETCH_BOARD'

export const FETCH_COMMENT_LIST = 'FETCH_COMMENT_LIST'
export const FETCH_COMMENT = "FETCH_COMMENT"

export const FETCH_REPLY_LIST = 'FETCH_REPLY_LIST'
export const FETCH_REPLY = "FETCH_REPLY"

export const FETCH_MEMBER = "FETCH_MEMBER"

export const FETCH_SESSION = "FETCH_SESSION"
export const REMOVE_SESSION = 'REMOVE_SESSION'
